# Generated by Django 5.1.1 on 2024-10-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('business', 'Business Owner'), ('worker', 'Private Worker')], default='worker', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subservices',
            field=models.ManyToManyField(blank=True, to='main.subservice'),
        ),
    ]
