# Generated by Django 5.1.1 on 2024-10-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_user_type_alter_profile_subservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('private', 'Private (Looking for Job)'), ('business', 'Business (Looking for Workers)')], default='private', max_length=10),
        ),
    ]
