# Generated by Django 5.1.1 on 2024-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_paidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subservices',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='main.subservice'),
        ),
    ]
