# Generated by Django 3.1.7 on 2021-03-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tvrtka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('godinaOsnivanja', models.IntegerField()),
                ('sjediste', models.CharField(max_length=100)),
                ('prihod', models.IntegerField(default=0)),
            ],
        ),
    ]
