# Generated by Django 3.1.7 on 2021-04-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvrtke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvrtka',
            name='logo',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
