# Generated by Django 3.1.7 on 2021-04-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plakat', models.ImageField(blank=True, upload_to='photos/%y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('released', models.CharField(blank=True, max_length=30)),
                ('body', models.TextField(blank=True)),
                ('display', models.TextField(blank=True)),
                ('platform', models.TextField(blank=True)),
                ('memory', models.TextField(blank=True)),
                ('camera', models.TextField(blank=True)),
                ('battery', models.TextField(blank=True)),
                ('misc', models.TextField(blank=True)),
                ('price', models.TextField(default=False)),
                ('sound', models.TextField(default=False)),
                ('features', models.TextField(default=False)),
                ('latest', models.BooleanField(default=False)),
            ],
        ),
    ]
