# Generated by Django 5.1.7 on 2025-03-11 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DubbingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='actors/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('original_title', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('croatia_dvd_release_date', models.DateField(blank=True, null=True)),
                ('croatia_bluray_release_date', models.DateField(blank=True, null=True)),
                ('us_dvd_release_date', models.DateField(blank=True, null=True)),
                ('us_bluray_release_date', models.DateField(blank=True, null=True)),
                ('poster_image', models.ImageField(upload_to='posters/')),
                ('dubbing_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.dubbingcompany')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='movies.movie')),
                ('voice_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.voiceactor')),
            ],
        ),
    ]
