# Generated by Django 5.1.7 on 2025-03-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubbingcompany',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dubbingcompany',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dubbingcompany',
            name='x',
            field=models.URLField(blank=True),
        ),
    ]
