# Generated by Django 5.1.7 on 2025-03-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_dubbingcompany_facebook_dubbingcompany_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceactor',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='x',
            field=models.URLField(blank=True),
        ),
    ]
