# Generated by Django 5.1.7 on 2025-03-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_episode_season_tvshow_episoderole_episode_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceactor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
