# Generated by Django 5.1.7 on 2025-03-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_voiceactor_date_of_birth_voiceactor_date_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierole',
            name='character_image',
            field=models.ImageField(blank=True, upload_to='characters/'),
        ),
    ]
