# Generated by Django 5.1.1 on 2025-04-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movierole_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceactor',
            name='dubbing_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_actors', to='movies.dubbingcompany'),
        ),
    ]
