# Generated by Django 5.1.1 on 2025-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_voiceactor_dubbing_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubbingcompany',
            name='logo',
            field=models.ImageField(blank=True, upload_to='companies/'),
        ),
    ]
