# Generated by Django 5.1.1 on 2025-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_dubbingcompany_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceactor',
            name='dubbing_company',
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='dubbing_companies',
            field=models.ManyToManyField(blank=True, related_name='voice_actors', to='movies.dubbingcompany'),
        ),
    ]
