# Generated by Django 3.1.7 on 2021-03-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tvrtke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('godina', models.IntegerField(default=2021)),
                ('zanr', models.CharField(max_length=50)),
                ('ocjena', models.DecimalField(decimal_places=1, max_digits=2)),
                ('trajanje', models.IntegerField()),
                ('redatelj', models.CharField(max_length=100)),
                ('glumci', models.TextField(blank=True)),
                ('kratkiSadrzaj', models.TextField(blank=True)),
                ('plakat', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('trailer', models.URLField(blank=True)),
                ('izdvojen', models.BooleanField(default=False)),
                ('tvrtka', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tvrtke.tvrtka')),
            ],
        ),
    ]
