# Generated by Django 3.1.7 on 2021-04-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvrtke', '0002_auto_20210429_1758'),
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Phone',
        ),
    ]
