# Generated by Django 3.1.7 on 2021-04-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20210429_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='glumci',
            new_name='battery',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='kratkiSadrzaj',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='izdvojen',
            new_name='latest',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='zanr',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='godina',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='naslov',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='ocjena',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='redatelj',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='trajanje',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='tvrtka',
        ),
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='display',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='frontCamera',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='mainCamera',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='memory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='misc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='platform',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='released',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='phone',
            name='plakat',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
