# Generated by Django 3.1.7 on 2021-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_auto_20210429_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='colors',
            field=models.TextField(default=False),
        ),
    ]
